export default class Cards {
  constructor() {
    this.entries = [
      ["Action (set A)", "Action (set B)", "Animal (set A)", "Animal (set B)", "Clothes", "Emotions", "Sport", "Occupations"],
      [
        {
          word: "cry",
          translation: "плакать",
          image: "./img/action a/cry.jpg",
          audioSrc: "./audio/action a/cry.mp3",
        },
        {
          word: "dance",
          translation: "танцевать",
          image: "./img/action a/dance.jpg",
          audioSrc: "./audio/action a/dance.mp3",
        },
        {
          word: "dive",
          translation: "нырять",
          image: "./img/action a/dive.jpg",
          audioSrc: "./audio/action a/dive.mp3",
        },
        {
          word: "draw",
          translation: "рисовать",
          image: "./img/action a/draw.jpg",
          audioSrc: "./audio/action a/draw.mp3",
        },
        {
          word: "fish",
          translation: "ловить рыбу",
          image: "./img/action a/fish.jpg",
          audioSrc: "./audio/action a/fish.mp3",
        },
        {
          word: "fly",
          translation: "летать",
          image: "./img/action a/fly.jpg",
          audioSrc: "./audio/action a/fly.mp3",
        },
        {
          word: "hug",
          translation: "обнимать",
          image: "./img/action a/hug.jpg",
          audioSrc: "./audio/action a/hug.mp3",
        },
        {
          word: "jump",
          translation: "прыгать",
          image: "./img/action a/jump.jpg",
          audioSrc: "./audio/action a/jump.mp3",
        },
      ],
      [
        {
          word: "open",
          translation: "открывать",
          image: "./img/action b/open.jpg",
          audioSrc: "./audio/action b/open.mp3",
        },
        {
          word: "play",
          translation: "играть",
          image: "./img/action b/play.jpg",
          audioSrc: "./audio/action b/play.mp3",
        },
        {
          word: "point",
          translation: "указывать",
          image: "./img/action b/point.jpg",
          audioSrc: "./audio/action b/point.mp3",
        },
        {
          word: "ride",
          translation: "ездить",
          image: "./img/action b/ride.jpg",
          audioSrc: "./audio/action b/ride.mp3",
        },
        {
          word: "run",
          translation: "бегать",
          image: "./img/action b/run.jpg",
          audioSrc: "./audio/action b/run.mp3",
        },
        {
          word: "sing",
          translation: "петь",
          image: "./img/action b/sing.jpg",
          audioSrc: "./audio/action b/sing.mp3",
        },
        {
          word: "skip",
          translation: "пропускать, прыгать",
          image: "./img/action b/skip.jpg",
          audioSrc: "./audio/action b/skip.mp3",
        },
        {
          word: "swim",
          translation: "плавать",
          image: "./img/action b/swim.jpg",
          audioSrc: "./audio/action b/swim.mp3",
        },
      ],
      [
        {
          word: "cat",
          translation: "кот",
          image: "./img/animal a/cat.jpg",
          audioSrc: "./audio/animal a/cat.mp3",
        },
        {
          word: "chick",
          translation: "цыплёнок",
          image: "./img/animal a/chick.jpg",
          audioSrc: "./audio/animal a/chick.mp3",
        },
        {
          word: "chicken",
          translation: "курица",
          image: "./img/animal a/chicken.jpg",
          audioSrc: "./audio/animal a/chicken.mp3",
        },
        {
          word: "dog",
          translation: "собака",
          image: "./img/animal a/dog.jpg",
          audioSrc: "./audio/animal a/dog.mp3",
        },
        {
          word: "horse",
          translation: "лошадь",
          image: "./img/animal a/horse.jpg",
          audioSrc: "./audio/animal a/horse.mp3",
        },
        {
          word: "pig",
          translation: "свинья",
          image: "./img/animal a/pig.jpg",
          audioSrc: "./audio/animal a/pig.mp3",
        },
        {
          word: "rabbit",
          translation: "кролик",
          image: "./img/animal a/rabbit.jpg",
          audioSrc: "./audio/animal a/rabbit.mp3",
        },
        {
          word: "sheep",
          translation: "овца",
          image: "./img/animal a/sheep.jpg",
          audioSrc: "./audio/animal a/sheep.mp3",
        },
      ],
      [
        {
          word: "bird",
          translation: "птица",
          image: "./img/animal b/bird.jpg",
          audioSrc: "./audio/animal b/bird.mp3",
        },
        {
          word: "fish",
          translation: "рыба",
          image: "./img/animal b/fish1.jpg",
          audioSrc: "./audio/animal b/fish.mp3",
        },
        {
          word: "frog",
          translation: "жаба",
          image: "./img/animal b/frog.jpg",
          audioSrc: "./audio/animal b/frog.mp3",
        },
        {
          word: "giraffe",
          translation: "жираф",
          image: "./img/animal b/giraffe.jpg",
          audioSrc: "./audio/animal b/giraffe.mp3",
        },
        {
          word: "lion",
          translation: "лев",
          image: "./img/animal b/lion.jpg",
          audioSrc: "./audio/animal b/lion.mp3",
        },
        {
          word: "mouse",
          translation: "мышь",
          image: "./img/animal b/mouse.jpg",
          audioSrc: "./audio/animal b/mouse.mp3",
        },
        {
          word: "turtle",
          translation: "черепаха",
          image: "./img/animal b/turtle.jpg",
          audioSrc: "./audio/animal b/turtle.mp3",
        },
        {
          word: "dolphin",
          translation: "дельфин",
          image: "./img/animal b/dolphin.jpg",
          audioSrc: "./audio/animal b/dolphin.mp3",
        },
      ],
      [
        {
          word: "skirt",
          translation: "юбка",
          image: "./img/clothes/skirt.jpg",
          audioSrc: "./audio/clothes/skirt.mp3",
        },
        {
          word: "pants",
          translation: "брюки",
          image: "./img/clothes/pants.jpg",
          audioSrc: "./audio/clothes/pants.mp3",
        },
        {
          word: "blouse",
          translation: "блузка",
          image: "./img/clothes/blouse.jpg",
          audioSrc: "./audio/clothes/blouse.mp3",
        },
        {
          word: "dress",
          translation: "платье",
          image: "./img/clothes/dress.jpg",
          audioSrc: "./audio/clothes/dress.mp3",
        },
        {
          word: "boot",
          translation: "ботинок",
          image: "./img/clothes/boot.jpg",
          audioSrc: "./audio/clothes/boot.mp3",
        },
        {
          word: "shirt",
          translation: "рубашка",
          image: "./img/clothes/shirt.jpg",
          audioSrc: "./audio/clothes/shirt.mp3",
        },
        {
          word: "coat",
          translation: "пальто",
          image: "./img/clothes/coat.jpg",
          audioSrc: "./audio/clothes/coat.mp3",
        },
        {
          word: "shoe",
          translation: "туфли",
          image: "./img/clothes/shoe.jpg",
          audioSrc: "./audio/clothes/shoe.mp3",
        },
      ],
      [
        {
          word: "sad",
          translation: "грустный",
          image: "./img/emotions/sad.jpg",
          audioSrc: "./audio/emotions/sad.mp3",
        },
        {
          word: "angry",
          translation: "сердитый",
          image: "./img/emotions/angry.jpg",
          audioSrc: "./audio/emotions/angry.mp3",
        },
        {
          word: "happy",
          translation: "счастливый",
          image: "./img/emotions/happy.jpg",
          audioSrc: "./audio/emotions/happy.mp3",
        },
        {
          word: "tired",
          translation: "уставший",
          image: "./img/emotions/tired.jpg",
          audioSrc: "./audio/emotions/tired.mp3",
        },
        {
          word: "surprised",
          translation: "удивлённый",
          image: "./img/emotions/surprised.jpg",
          audioSrc: "./audio/emotions/surprised.mp3",
        },
        {
          word: "scared",
          translation: "испуганный",
          image: "./img/emotions/scared.jpg",
          audioSrc: "./audio/emotions/scared.mp3",
        },
        {
          word: "smile",
          translation: "улыбка",
          image: "./img/emotions/smile.jpg",
          audioSrc: "./audio/emotions/smile.mp3",
        },
        {
          word: "laugh",
          translation: "смех",
          image: "./img/emotions/laugh.jpg",
          audioSrc: "./audio/emotions/laugh.mp3",
        },
      ],
      [
        {
          word: "football",
          translation: "футбол",
          image: "./img/sport/football.jpg",
          audioSrc: "./audio/sport/football.mp3",
        },
        {
          word: "volleyball",
          translation: "волейбол",
          image: "./img/sport/volleyball.jpg",
          audioSrc: "./audio/sport/volleyball.mp3",
        },
        {
          word: "basketball",
          translation: "баскетбол",
          image: "./img/sport/basketball.jpg",
          audioSrc: "./audio/sport/basketball.mp3",
        },
        {
          word: "hockey",
          translation: "хоккей",
          image: "./img/sport/hockey.jpg",
          audioSrc: "./audio/sport/hockey.mp3",
        },
        {
          word: "tennis",
          translation: "теннис",
          image: "./img/sport/tennis.jpg",
          audioSrc: "./audio/sport/tennis.mp3",
        },
        {
          word: "boxing",
          translation: "бокс",
          image: "./img/sport/boxing.jpg",
          audioSrc: "./audio/sport/boxing.mp3",
        },
        {
          word: "biathlon",
          translation: "биатлон",
          image: "./img/sport/biathlon.jpg",
          audioSrc: "./audio/sport/biathlon.mp3",
        },
        {
          word: "baseball",
          translation: "бейсбол",
          image: "./img/sport/baseball.jpg",
          audioSrc: "./audio/sport/baseball.mp3",
        },
      ],
      [
        {
          word: "artist",
          translation: "художник",
          image: "./img/occupations/artist.jpg",
          audioSrc: "./audio/occupations/artist.mp3",
        },
        {
          word: "ballerina",
          translation: "балерина",
          image: "./img/occupations/ballerina.jpg",
          audioSrc: "./audio/occupations/ballerina.mp3",
        },
        {
          word: "builder",
          translation: "строитель",
          image: "./img/occupations/builder.jpg",
          audioSrc: "./audio/occupations/builder.mp3",
        },
        {
          word: "butcher",
          translation: "мясник",
          image: "./img/occupations/butcher.jpg",
          audioSrc: "./audio/occupations/butcher.mp3",
        },
        {
          word: "doctor",
          translation: "врач",
          image: "./img/occupations/doctor.jpg",
          audioSrc: "./audio/occupations/doctor.mp3",
        },
        {
          word: "nurse",
          translation: "медсестра",
          image: "./img/occupations/nurse.jpg",
          audioSrc: "./audio/occupations/nurse.mp3",
        },
        {
          word: "seller",
          translation: "продавец",
          image: "./img/occupations/seller.jpg",
          audioSrc: "./audio/occupations/seller.mp3",
        },
        {
          word: "teacher",
          translation: "бейсбол",
          image: "./img/occupations/teacher.jpg",
          audioSrc: "./audio/occupations/teacher.mp3",
        },
      ],
    ];
  }
}
